### ISSUE TITLE
Is there any way of running rqt_graph 1.0 in kinetic?

### ISSUE THREAD

**Issue by martinakos** [ros-visualization/rqt_graph#24]
I'd like to benefit from the improvement in rqt_graph 1.0 but I'm stuck with kinetic. Is there any way I could run the latest rqt_graph in kinetic?

**Comment by dirk-thomas** [comment]
Version 1.0 is from the crystal-devel branch which targets ROS 2. No, you can't use that with any ROS 1 distribution.

If there are any particular improvements on the ROS 2 branch I would assume it should be possible to backport those to the ROS 1 branch. Please feel free to point those out explicitly and/or provide a pull request doing the backport.

Since there is nothing specific to be done at the moment I will go ahead and close this ticket. Please feel free to continue commenting and if needed the ticket can be reopened.

**Comment by 0novanta** [comment]
Any chance of this being related to my issue #25 ?

**Comment by dirk-thomas** [comment]
> Any chance of this being related to my issue #25 ?

You are neither mentioning in the referenced ticket which branch  nor which Python version you are using. Without more information I can't help.
